#list
L=['Michael','Srach','Tracy','Bob','Jack']
print(L)
print(L[0:3])#从索引0开始，截取到索引3，但是不包含3
print(L[:3])
print(L[1:3])
print(L[-2:-1])
print(L[-1])
list=list(range(100))
print(list)
print(list[:10])
print(list[-10:])
print(list[10:20])
print(list[:10:2])
print(list[::5])
print('=======')
print(list)
#tuple
tuple=tuple(range(20))
print(tuple)
print(tuple[:])
print(tuple[::2])